name: Workflow basico
on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
steps:
  -name=Comrpobar código fuente
  uses:actions/checkout@v2
run: echo ${{secrets.REPOSITORIO_SECRETO}}

run:
  npm start test
