name: Run Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Configurar Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install
    - run: npm test

  build:
    runs-on: ubuntu-latest
    
    steps:
    - run: npm install
    - run: npm test

